# Generated by Django 3.2.13 on 2022-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户名')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='类型')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='歌曲id')),
                ('song_list_id', models.IntegerField(blank=True, null=True, verbose_name='歌单id')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'collect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='评论id')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='类型')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='歌曲id')),
                ('song_list_id', models.IntegerField(blank=True, null=True, verbose_name='歌单id')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('up', models.IntegerField(blank=True, null=True, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='电子邮箱')),
                ('birth', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('avator', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'consumer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(blank=True, null=True, verbose_name='歌曲id')),
                ('song_list_id', models.IntegerField(blank=True, null=True, verbose_name='歌单id')),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'db_table': 'list_song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_list_id', models.IntegerField(verbose_name='歌单id')),
                ('consumer_id', models.IntegerField(verbose_name='用户id')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'db_table': 'rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField(blank=True, null=True, verbose_name='歌手id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像地址')),
                ('lyric', models.TextField(blank=True, null=True, verbose_name='歌词')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='歌曲链接')),
            ],
            options={
                'verbose_name': '排行榜信息',
                'verbose_name_plural': '排行榜信息',
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='性别')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='照片')),
                ('birth', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '歌手信息',
                'verbose_name_plural': '歌手信息',
                'db_table': 'singer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.IntegerField(blank=True, null=True, verbose_name='歌手id')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓名')),
                ('introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像地址')),
                ('lyric', models.TextField(blank=True, null=True, verbose_name='歌词')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='歌曲链接')),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('style', models.CharField(blank=True, max_length=255, null=True, verbose_name='风格')),
            ],
            options={
                'verbose_name': '歌单信息',
                'verbose_name_plural': '歌单信息',
                'db_table': 'song_list',
                'managed': False,
            },
        ),
    ]
